//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 08:27:00 PM IST 
//


package com.javatechie.spring.soap.api.loaneligibility;

import javax.xml.bind.annotation.XmlRegistry;


@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {}

    public CustomerRequest createCustomerRequest() {
        return new CustomerRequest();
    }

    public Acknowledgement createAcknowledgement() {
        return new Acknowledgement();
    }

}
